### ISSUE TITLE
Beverage Recipes

### ISSUE THREAD

**Issue by RogerWDavis** [RogerWDavis/DrinkTank#1]
As a user I can browse the specific category landing pages so as to see the available beverage recipes.

# Acceptance Criteria
All related beverage recipes are neatly displayed on category landing page.
Authenticated user can see the option to like and download recipes.
Authenticated user can see the option to upload recipes.
## Tasks
- [ ]  Display recipes in scrollable 4x2 grid using flexbox to allow for a responsive layout.
- [ ]  Display "Like" button that displays previous likes and that, when clicked, informs the user that the like was successful.
- [ ]  Display "Download" button that downlaods the recipe to the user.
- [ ]  Display "Upload" button that allows the user to upload a recipe.
