### ISSUE TITLE
Landing Page Design

### ISSUE THREAD

**Issue by RogerWDavis** [RogerWDavis/DrinkTank#2]
As a user I can use the site URL so as to arrive at the site landing page.

# Acceptance Criteria
Using the site URL delivers the user to the landing page
The landing page prompts user to log-in/sign-up
## Tasks
- [ ]  Create the Front end (HTML and CSS) page design to be displayed when the landing page loads that includes:
* Log in/Sign up funtionality.
* A sign in success message.
* An alternate view for authenticated users.
- [ ] Create links for alchohol categories and style with photos.
- [ ] Create about us section to describe site usage.
